NAME: FlowNetC
ENCODER:
  NAME: FlowNetConvEncoder
  IN_CHANNELS: 3
  CONFIG: [64, 128, 256, 256, 512, 512, 512, 512, 1024, 1024]
  NORM: batch
SIMILARITY:
  NAME: IterSpatialCorrelationSampler
  PAD_SIZE: 0
  MAX_DISPLACEMENT: 10
DECODER:
  NAME: FlowNetConvDecoder
  IN_CHANNELS: 1024
  CONFIG: [512, 256, 128, 64]