DATA:
  BATCH_SIZE: 8
  NUM_WORKERS: 4
  PIN_MEMORY: True
  SHUFFLE: True
  INIT_SEED: False
  DROP_LAST: True
  TRAIN_DATASET:
    FlyingChairs:
      ROOT_DIR: "./Datasets/FlyingChairs_release/data"
      SPLIT: "training"
      IS_PREDICTION: False
      APPEND_VALID_MASK: False
      CROP: 
        USE: True
        SIZE: [384, 448]
        TYPE: "random"
      FLOW_OFFSET_PARAMS: {"use": False}
      AUGMENTATION:
        # Augmentation Settings borrowed from RAFT
        USE: True
        PARAMS:
          color_aug_params: {
            "enabled": True,
            "asymmetric_color_aug_prob": 0.2, 
            "brightness": 0.4, 
            "contrast": 0.4, 
            "saturation": 0.4, 
            "hue": 0.15915494309189535
          }
          eraser_aug_params: {
            "enabled": True,
            "aug_prob": 0.5,
            "bounds": [50, 100]
          }
          noise_aug_params: {
            "enabled": False,
            "aug_prob": 0.5,
            "noise_std_range": 0.06 
          }
          flip_aug_params: {
            "enabled": True, 
            "h_flip_prob": 0.5, 
            "v_flip_prob": 0.1
          }
          spatial_aug_params: {
            "enabled": True,
            "aug_prob": 0.8, 
            "stretch_prob": 0.8, 
            "min_scale": -0.1, 
            "max_scale": 1.0, 
            "max_stretch": 0.2, 
          }
          advanced_spatial_aug_params: {
            "enabled": False,
            "scale1": 0.0,
            "scale2": 0.0,
            "stretch": 0.0,
            "rotate": 0.0,
            "translate": 0.0,
            "enable_out_of_boundary_crop": False
          }
  VAL_DATASET:
    FlyingChairs:
      ROOT_DIR: "./Datasets/FlyingChairs_release/data"
      SPLIT: "validation"
      APPEND_VALID_MASK: False
      IS_PREDICTION: False
      PADDING: 1
      CROP: 
        USE: False
      FLOW_OFFSET_PARAMS: {"use": False}
      AUGMENTATION:
        USE: False
OPTIMIZER:
  NAME: AdamW
  LR: 0.0004
  PARAMS:
    weight_decay: 0.0001
    betas: [0.9, 0.999]
    eps: 1.e-08
    amsgrad: False
GRAD_CLIP: 
  USE: True
  VALUE: 1.0
FREEZE_BATCH_NORM: False
TARGET_SCALE_FACTOR: 1.0
MIXED_PRECISION: False
DEVICE: "0"
DISTRIBUTED:
  USE: False
  WORLD_SIZE: 2
  BACKEND: nccl
  MASTER_ADDR: localhost
  MASTER_PORT: "12355"
EPOCHS: null
NUM_STEPS: null
RESUME_TRAINING:
  CONSOLIDATED_CKPT: null
  EPOCHS: null
  START_EPOCH: null