DATA:
  BATCH_SIZE: 6
  APPEND_VALID_MASK: False
  NUM_WORKERS: 4
  PIN_MEMORY: True
  SHUFFLE: True
  INIT_SEED: False
  DROP_LAST: True
  TRAIN_DATASET:
    Kubric:
      ROOT_DIR: "./Datasets/KubricFlow"
      SPLIT: "training"
      USE_BACKWARD_FLOW: False
      SWAP_COLUMN_TO_ROW: True
      IS_PREDICTION: False
      APPEND_VALID_MASK: False
      CROP: 
        USE: True
        SIZE: [384, 448]
        TYPE: "random"
      FLOW_OFFSET_PARAMS: {"use": False}
      AUGMENTATION:
        # Spatial Augmentation Settings borrowed from AutoFlow: https://github.com/google-research/opticalflow-autoflow/blob/main/src/dataset_lib/augmentations/aug_params.py
        USE: True
        PARAMS:
          TRAINING:
            COLOR_AUG_PARAMS: {
              "enabled": True,
              "asymmetric_color_aug_prob": 0.2, 
              "brightness": 0.4, 
              "contrast": 0.4, 
              "saturation": 0.4, 
              "hue": 0.15915494309189535
            }
            ERASER_AUG_PARAMS: {
              "enabled": True,
              "aug_prob": 0.5,
              "bounds": [50, 100]
            }
            NOISE_AUG_PARAMS: {
              "enabled": True,
              "aug_prob": 0.5,
              "noise_std_range": 0.06 
            }
            FLIP_AUG_PARAMS: {
              "enabled": True, 
              "h_flip_prob": 0.5, 
              "v_flip_prob": 0.1
            }
            SPATIAL_AUG_PARAMS: {
              "enabled": False,
              "aug_prob": 0.0, 
              "stretch_prob": 0.0, 
              "min_scale": 0, 
              "max_scale": 0, 
              "max_stretch": 0
            }
            ADVANCED_SPATIAL_AUG_PARAMS: {
              "enabled": True,
              "scale1": 0.3,
              "scale2": 0.1,
              "rotate": 0.4,
              "translate": 0.4,
              "stretch": 0.3,
              "enable_out_of_boundary_crop": False
            }
  VAL_DATASET:
    Kubric: 
      ROOT_DIR: "./Datasets/KubricFlow"
      SPLIT: "validation"
      USE_BACKWARD_FLOW: False
      SWAP_COLUMN_TO_ROW: True
      APPEND_VALID_MASK: False
      IS_PREDICTION: False
      PADDING: 1
      CROP: 
        USE: True
        SIZE: [384, 448]
        TYPE: "center"
      FLOW_OFFSET_PARAMS: {"use": False}
      AUGMENTATION:
        USE: False
        PARAMS:
          color_aug_params: {"enabled": False}
          eraser_aug_params: {"enabled": False}
          noise_aug_params: {"enabled": False}
          flip_aug_params: {"enabled": False}
          spatial_aug_params: {"enabled": False}
          advanced_spatial_aug_params: {"enabled": False}        
OPTIMIZER:
  NAME: AdamW
  LR: 0.0004
  PARAMS:
    weight_decay: 0.0001
    betas: [0.9, 0.999]
    eps: 1.e-08
    amsgrad: False
GRAD_CLIP: 
  USE: True
  VALUE: 1.0
FREEZE_BATCH_NORM: False
TARGET_SCALE_FACTOR: 1.0
MIXED_PRECISION: False
DEVICE: "0"
DISTRIBUTED:
  USE: False
  WORLD_SIZE: 2
  BACKEND: nccl
  MASTER_ADDR: localhost
  MASTER_PORT: "12355"
EPOCHS: null
NUM_STEPS: null
RESUME_TRAINING:
  CONSOLIDATED_CKPT: null
  EPOCHS: null
  START_EPOCH: null